
export const properties = [
    {
        id: "1",
        title: "Modern Luxury Apartment",
        location: "Manhattan, new york",
        price: 250000,
        type: "Apartment",
        status: "rent",
        bedrooms: 4,
        bathrooms: 3,
        area: 2200,
        featured: true,
        imageUrl: "../../public/images/image1.jpg",
        description: "A beautiful modern apartment located in the heart of the city.",
    },
    {
        id: "2",
        title: "Local Apartment",
        location: "Manhattan, new york",
        price: 210000,
        type: "Apartment",
        status: "rent",
        bedrooms: 4,
        bathrooms: 3,
        area: 1800,
        featured: true,
        imageUrl: "/images/image2.jpg",
        description: "A beautiful modern apartment located in the heart of the city.",
    },
    {
        id: "3",
        title: "Simple Apartment",
        location: "Manhattan, new york",
        price: 220000,
        type: "Apartment",
        status: "rent",
        bedrooms: 4,
        bathrooms: 3,
        area: 2000,
        featured: true,
        imageUrl: "/images/image3.jpg",
        description: "A beautiful modern apartment located in the heart of the city.",
    },
    {
        id: "4",
        title: "Downtown Apartment",
        location: "Manhattan, new york",
        price: 150000,
        type: "Apartment",
        status: "rent",
        bedrooms: 4,
        bathrooms: 3,
        area: 1600,
        featured: true,
        imageUrl: "/images/image4.jpg",
        description: "A beautiful modern apartment located in the heart of the city.",
    },
    {
        id: "5",
        title: "High Building Apartment",
        location: "Manhattan, new york",
        price: 150000,
        type: "Apartment",
        status: "rent",
        bedrooms: 4,
        bathrooms: 3,
        area: 1700,
        featured: true,
        imageUrl: "/images/image5.jpg",
        description: "A beautiful modern apartment located in the heart of the city.",
    },
    {
        id: "6",
        title: "Complex Luxury Apartment",
        location: "Manhattan, new york",
        price: 290000,
        type: "Apartment",
        status: "rent",
        bedrooms: 4,
        bathrooms: 3,
        area: 2600,
        featured: true,
        imageUrl: "/images/image6.jpg",
        description: "A beautiful modern apartment located in the heart of the city.",
    }
]